In [1]:
import numpy as np
arr1=np.array([1,2,3,6,4,5])
print(arr1)
np.flip(arr1)

[1 2 3 6 4 5]


array([5, 4, 6, 3, 2, 1])

In [2]:
a1D =np.array([1,2,3,4])
a2D=np.array([[1,2],[3,4]])
a3D=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
print(a3D.ndim)
print(a3D.shape)
print(a3D.size)
print(a3D.dtype)
print(a3D.itemsize)

3
(2, 2, 2)
8
int64
8


In [4]:
print(a1D.ndim)
print(a1D.shape)
print(a1D.size)
print(a1D.dtype)
print(a1D.itemsize)

1
(4,)
4
int64
8


In [5]:
a=np.array([1,2,3,45],dtype=float)
print(a)

[ 1.  2.  3. 45.]


In [6]:
a=np.array([1,2,3,45],dtype=complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j 45.+0.j]


In [7]:
a=np.array([1,2,3,45],dtype=bool)
print(a)

[ True  True  True  True]


In [8]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr=np.arange(2,10,3,dtype=float)
print(arr)

[2. 5. 8.]


In [10]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [11]:
np.eye(3,3,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [12]:
np.eye(3,5,k=0,dtype=int)
#k is diag val where you want 1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [13]:
np.diag([[1,2,3],[4,5,6],[7,8,9]])

array([1, 5, 9])

In [14]:
np.vander([1,2,3,4],N=4,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [15]:
np.vander([1,2,3,4],N=3,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [16]:
np.ones((5,4,3),dtype=int,like=None)
# first number tells number of matrices

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [17]:
np.zeros((4,2,3),dtype=None,order='C',like=None)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
b = np.zeros((3, 2, 3),dtype=int,order='F')
print(b)


[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [19]:
np.empty((2,3))

array([[1. , 1.6, 2.2],
       [2.8, 3.4, 4. ]])

In [20]:
a=np.array([1,2,3,4,5,6])
a=a.reshape((2,3))

In [21]:
b=a[:4]
b+=1
print(b)

[[2 3 4]
 [5 6 7]]


In [22]:
c=a.copy()
print(c)

[[2 3 4]
 [5 6 7]]


In [23]:
A=np.zeros((2,2),dtype=int)
B=np.ones((2,2),dtype=int)
np.concatenate((B,A),axis=1)

array([[1, 1, 0, 0],
       [1, 1, 0, 0]])

In [24]:
np.block([A,B])

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

In [25]:
np.vstack((A,B))

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1]])

In [26]:
np.hstack((A,B))

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

In [27]:
#a = np.loadtxt('D:/prc.txt', dtype=int, delimiter=',')


In [28]:
np.random.rand(2,3)

array([[0.05833514, 0.36313787, 0.7737563 ],
       [0.92103139, 0.21301503, 0.02651095]])

In [29]:
d=np.array([i for i in range(0,25)]).reshape((5,5))
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [30]:
a=np.array([1,2,3,4,7,9,5,6])
a=a.reshape((4,2))
print(a)

[[1 2]
 [3 4]
 [7 9]
 [5 6]]


In [31]:
a=a.flatten()
print(a)

[1 2 3 4 7 9 5 6]


In [32]:
c=1,2,3,4
X=np.array(c)
print(X)
m=np.asmatrix(c)
print(m)

[1 2 3 4]
[[1 2 3 4]]


In [33]:
np.asfarray(c)

array([1., 2., 3., 4.])

In [34]:
X = np.array([42])  # Example array
scalar = X.item()
print(scalar)

42


In [35]:
x=np.arange(1,12,2)
print(x)
#np.split(x,3)
np.hsplit(x,3)

[ 1  3  5  7  9 11]


[array([1, 3]), array([5, 7]), array([ 9, 11])]

In [36]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
np.delete(arr,0,1)

array([[2, 3, 4],
       [6, 7, 8]])

In [37]:
arr=np.array([[1,1],[2,2]])
np.insert(arr,1,1)

array([1, 1, 1, 2, 2])

In [38]:
np.append([[1,2,3],[5,6,7]],[[9],[4]],axis=1)

array([[1, 2, 3, 9],
       [5, 6, 7, 4]])

In [39]:
a=np.array((0,0,0,1,2,3,0,1,0))
np.trim_zeros(a)

array([1, 2, 3, 0, 1])

In [40]:
a=np.array((0,0,0,2,3,0,1,0))
np.unique(a)

array([0, 1, 2, 3])

In [41]:
a=np.array([[4,1],[3,1]])
np.sort(a)

array([[1, 4],
       [1, 3]])

In [42]:
a=np.array([[4,6],[3,1]])
np.argsort(a)

array([[0, 1],
       [1, 0]])

In [43]:
a=np.array([[4,1,2,3]])
np.partition(a,3)

array([[2, 1, 3, 4]])

In [44]:
a=np.arange(6).reshape(2,3)+10
print(a)
np.argmax(a)

[[10 11 12]
 [13 14 15]]


5

In [45]:
a=np.array([[np.nan,4],[2,6]])
np.nanargmax(a)

3

In [46]:
a=np.array([[np.nan,4],[2,6]])
np.argmin(a)

0

In [47]:
a=np.array([[3,0,0],[0,4,0],[5,6,0]])
np.nonzero(a)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [48]:
a=np.array([[3,0,0],[0,4,0],[5,6,0]])
np.flatnonzero(a)

array([0, 4, 6, 7])

In [49]:
a = np.arange(10)
np.where(a < 5, a, 10*a)


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [50]:
np.count_nonzero(np.eye(4))


4

In [51]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)


array([[4, 1],
       [2, 2]])

In [52]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.inner(a, b)


array([[4, 2],
       [1, 2]])

In [53]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)


array([[4, 1],
       [2, 2]])

In [54]:
a = [[5, 3], [2, 1]]
np.linalg.matrix_power(a,2)


array([[31, 18],
       [12,  7]])

In [55]:
b = [[4, 1], [2, 2]]
u,s,v=np.linalg.svd(b)


In [56]:
b = [[4, 1], [2, 2]]
value,vector=np.linalg.eig(b)
print(value,vector)

[4.73205081 1.26794919] [[ 0.80689822 -0.34372377]
 [ 0.59069049  0.9390708 ]]


In [57]:
b = [[4, 1], [2, 2]]
value=np.linalg.norm(b)
print(value)

5.0


In [58]:
b = [[4, 1], [0, 0]]
value=np.linalg.matrix_rank(b)
print(value)

1


In [59]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
print(x)

[-1.  1.]


In [60]:
a = np.array([[1, 2], [3, 5]])
x = np.linalg.inv(a)
print(x)

[[-5.  2.]
 [ 3. -1.]]


In [61]:
a = np.array([[1, 2], [3, 5]])
np.median(a)


2.5

In [62]:
np.average(np.arange(1, 11), weights=np.arange(10, 0, -1))


4.0

In [63]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)


2.5

In [64]:
a = np.array([[1, 2], [3, 5]])
np.std(a)


1.479019945774904

In [65]:
a = np.array([[1, 2], [3, 5]])
np.var(a)


2.1875

In [66]:
a = np.array([[1, 2], [3, 5]])
np.corrcoef(a)


array([[1., 1.],
       [1., 1.]])

In [67]:
a = np.array([[1, 2], [3, 5]])
np.cov(a)


array([[0.5, 1. ],
       [1. , 2. ]])

In [68]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 50)


3.5

In [69]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 0.5)


1.025